emergency_management/urls.py
from django.conf.urls import patterns, include, url

from django.contrib.auth import views as auth_views
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',

    # Examples:
    # url(r'^$', 'emergency_management.views.home', name='home'),
    # url(r'^emergency_management/', include('emergency_management.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    #url(r'^rosetta/', include('rosetta.urls')),

    url(r'^accounts/login/$', auth_views.login,
        {'template_name': 'login.html'}, name='auth_login'),
    url(r'^accounts/logout/$', auth_views.logout,
        {'template_name': 'login.html'}, name='auth_logout'),
    url(r'^translate/', include('rosetta.urls')),
    url(r'^reports/', include('report.urls')),
    url(r'^', include('incident.urls')),
)

incident/urls.py
__LICENSE__ = '''Copyright (C) 2012 "Emanuel Calso" <eman@bloodpet.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see
http://www.gnu.org/licenses/agpl-3.0.html.
'''


from django.utils.translation import ugettext_lazy as _lazy, ugettext as _
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from incident.views import *


urlpatterns = patterns(
    'incident.views',
    url(r'^$', login_required(HomeView.as_view()),
        {'template': 'home.html'}, name='home'),
    url(r'^gotopage/$', login_required(GotoPage.as_view()),
        name='gotopage'),
    url(r'^create_associated/$', login_required(CreateAssociated.as_view()),
        name='create_associated'),
    # Alert URLs
    url(r'^alert/create/$',
        login_required(AlertCreateView.as_view()),
        name='alert_create'),
    url(r'alert/read/(?P<pk>\d+)/$',
        login_required(AlertDetailView.as_view()),
        name='alert_details'),
    url(r'alert/edit/(?P<pk>\d+)/$',
        login_required(AlertUpdateView.as_view()),
        name='alert_edit'),
    url(r'alert/associate/(?P<pk>\d+)/$',
        login_required(AlertAssociateView.as_view()),
        name='alert_associate'),
    url(r'^associate_alerts/$',
        login_required(AlertListAssociateView.as_view()),
        name='associate_alerts'),
    url(r'^alert/$',
        login_required(AlertListView.as_view()),
        name='alert_list'),
    # Occurrence URLs
    url(r'^occurrence/create/$',
        login_required(OccurrenceCreateView.as_view()),
        name='occurrence_create'),
    url(r'occurrence/read/(?P<pk>\d+)/$',
        login_required(OccurrenceDetailView.as_view()),
        name='occurrence_details'),
    url(r'occurrence/edit/(?P<pk>\d+)/$',
        login_required(OccurrenceUpdateView.as_view()),
        name='occurrence_edit'),
    url(r'occurrence/associate/(?P<pk>\d+)/$',
        login_required(OccurrenceAssociateView.as_view()),
        name='occurrence_associate'),
    url(r'occurrence/alerts/(?P<pk>\d+)/$',
        login_required(OccurrenceAlertsView.as_view()),
        name='occurrence_alerts'),
    url(r'occurrence/occurrences/(?P<pk>\d+)/$',
        login_required(OccurrenceOccurrencesView.as_view()),
        name='occurrence_occurrences'),
    url(r'^occurrence/$',
        login_required(OccurrenceListView.as_view()),
        name='occurrence_list'),
    url(r'^associate_occurrences/$',
        login_required(OccurrenceListAssociateView.as_view()),
        name='associate_occurrences'),
    url(r'occurrence/(?P<pk>\d+)/dispatches/$',
        login_required(OccurrenceDispatchListView.as_view()),
        name='dispatches'),
    url(r'occurrence/(?P<occurrence_pk>\d+)/dispatch/$',
        login_required(DispatchEntityListView.as_view()),
        name='dispatch_choose_entity'),
    url(r'occurrence/(?P<occurrence_pk>\d+)/dispatch/(?P<entity_pk>\d+)$',
        login_required(DispatchVehicleListView.as_view()),
        name='dispatch_choose_vehicle'),
    url(r'occurrence/(?P<occurrence_pk>\d+)/dispatch/create$',
        login_required(OccurrenceDispatchCreateView.as_view()),
        name='dispatch_create'),
    url(r'occurrence/(?P<occurrence_pk>\d+)/dispatch/edit/(?P<pk>\d+)$',
        login_required(OccurrenceDispatchUpdateView.as_view()),
        name='dispatch_edit'),
)


# vim: set noexpandtab ts=4 sw=4

report/urls.py
__LICENSE__ = '''Copyright (C) 2012 "Emanuel Calso" <eman@bloodpet.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see
http://www.gnu.org/licenses/agpl-3.0.html.
'''


from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from report.views import *


urlpatterns = patterns(
    'report.views',
    url(r'^end_shift/$', login_required(EndShiftReport.as_view()),
        {'template': 'reports/end_shift.html'}, name='end_shift'),
)

incident/models.py
__LICENSE__ = '''Copyright (C) 2012 "Emanuel Calso" <eman@xaasy.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see
http://www.gnu.org/licenses/agpl-3.0.html.
'''


from emergency_management import models
from django.utils.translation import ugettext_lazy as _lazy, ugettext as _
from django.contrib.auth.models import User
from django.utils.encoding import smart_unicode
from location.models import District, County, Locality
from operation_resource.models import (
    Entity, Vehicle
)


class Foreigners(object):

    def get_foreign_key(self, key, pk):
        foreign_keys = dict(
            alert=Alert,
            occurrence=Occurrence,
            nature=Nature,
            source=Source,
            source_type = SourceType,
            status=Status,
            importance=Importance,
            entity=Entity,
            district=District,
            county=County,
            locality=Locality,
        )
        return foreign_keys[key].objects.get(pk=pk)


class Importance(models.NamedModel):
    name = models.CharField(_(u'Name'), max_length=64)
    number = models.PositiveIntegerField(_(u'Number'), unique=True)

    class Meta:
        verbose_name = _(u'Importance')
        verbose_name_plural = _(u'Importances')
        verbose_name = _lazy(u'Importance')
        verbose_name_plural = _lazy(u'Importances')


class Status(models.NamedModel):
    name = models.CharField(_(u'Name'), max_length=256)

    class Meta:
        verbose_name = _(u'Status')
        verbose_name_plural = _(u'statuses')
        verbose_name = _lazy(u'Status')
        verbose_name_plural = _lazy(u'statuses')


class NatureFamily(models.Model):
    name = models.CharField(_(u'Name'), max_length=256)
    abbr = models.CharField(_(u'Abbreviation'), max_length=16)
    number = models.PositiveIntegerField(
        _(u'Number'), serialize=True,
        auto_created=True,
        unique_for_year='start_ts')

    class Meta:
        verbose_name = _(u'nature family')
        verbose_name_plural = _(u'nature families')
        verbose_name = _lazy(u'nature family')
        verbose_name_plural = _lazy(u'nature families')

    def __unicode__(self):
        return self.name


class NatureType(models.Model):
    nature_family = models.ForeignKey(NatureFamily, verbose_name=_(u'Family'))
    name = models.CharField(_(u'Name'), max_length=256)
    abbr = models.CharField(_(u'Abbreviation'), max_length=16)
    number = models.PositiveIntegerField(
        _(u'Number'), serialize=True,
        auto_created=True,
        unique_for_year='start_ts')

    class Meta:
        verbose_name = _(u'nature subfamily')
        verbose_name_plural = _(u'nature subfamilies')
        verbose_name = _lazy(u'nature subfamily')
        verbose_name_plural = _lazy(u'nature subfamilies')

    def __unicode__(self):
        return self.name


class Nature(models.Model):
    nature_type = models.ForeignKey(NatureType, verbose_name=_(u'Type'))
    name = models.CharField(_(u'Name'), max_length=256, blank=True)
    number = models.PositiveIntegerField(
        _(u'Number'), serialize=True,
        auto_created=True, default=0,
        unique_for_year='start_ts')

    class Meta:
        verbose_name = _(u'Nature')
        verbose_name_plural = _(u'Natures')
        verbose_name = _lazy(u'Nature')
        verbose_name_plural = _lazy(u'Natures')

    def __unicode__(self):
        txt = u'%s %s / %s' % ((
            ((1000 * self.nature_type.nature_family.number) +\
             (100 * self.nature_type.number) + self.number)),
            smart_unicode(self.nature_type.nature_family.abbr),
            smart_unicode(self.nature_type.abbr),
        )
        if self.name:
            txt += u' / ' + smart_unicode(self.name)
        return txt


class Source(models.NamedModel):
    name = models.CharField(_(u'Name'), max_length=256)

    class Meta:
        verbose_name = _(u'Source')
        verbose_name_plural = _(u'Sources')
        verbose_name = _lazy(u'Source')
        verbose_name_plural = _lazy(u'Sources')


class SourceType(models.NamedModel):
    name = models.CharField(_(u'Name'), max_length=256)

    class Meta:
        verbose_name = u'%s %s/%s' % (_(u'Source'), _('Entity'), _('Citizen'))
        verbose_name_plural = u'%s %s/%s' % (_(u'Source'), _('Entities'), _('Citizens'))
        verbose_name = u'%s %s/%s' % (_lazy(u'Source'), _lazy('Entity'), _lazy('Citizen'))
        verbose_name_plural = u'%s %s/%s' % (_lazy(u'Source'), _lazy('Entities'), _lazy('Citizens'))


class Alert(models.SerializedModel):
    user = models.ForeignKey(User, editable=False)
    occurrence = models.ForeignKey('Occurrence', blank=True, null=True, editable=False)
    number = models.PositiveIntegerField(
        _(u'Number'), serialize=True, default=0,
        auto_created=True, editable=False,
        unique_for_year='start_ts')
    start_ts = models.DateTimeField(
        _(u'Time'), auto_now_add=True, editable=False)
    end_ts = models.DateTimeField(
        _(u'Time Ended'), editable=False, null=True)
    nature = models.ForeignKey(Nature, verbose_name=_('Nature'), default=1)
    description = models.TextField(_(u'Description'), blank=True)
    source = models.ForeignKey(Source, verbose_name=_(u'Source'), blank=True, null=True)
    source_type = models.ForeignKey(
        SourceType,
        verbose_name=u'%s %s/%s' % (_(u'Source'), _('Entity'), _('Citizen')),
        blank=True, null=True)
    name = models.CharField(_(u'Name'), max_length=256, blank=True)
    phone = models.CharField(_(u'Phone'), max_length=32, blank=True)
    # Location Fields
    district = models.ForeignKey(District, verbose_name=_(u'District'), blank=True, null=True)
    county = models.ForeignKey(County, verbose_name=_(u'Subdistrict'), blank=True, null=True)
    locality = models.ForeignKey(Locality, verbose_name=_(u'Suco'), blank=True, null=True)
    local = models.CharField(_(u'Aldea'), max_length=256, blank=True)
    point_of_reference = models.TextField(_(u'Point of Reference'), blank=True)
    # Geolocation Fields
    latitude = models.FloatField(_(u'Latitude'), blank=True, null=True)
    longitude = models.FloatField(_(u'Longitude'), blank=True, null=True)
    # False alarm
    is_false = models.BooleanField(verbose_name=_(u'False Alert'), default=False)

    @models.permalink
    def get_absolute_url(self):
        return ('alert_edit', [self.pk, ])


class Occurrence(models.SerializedModel):
    user = models.ForeignKey(User, editable=False)
    occurrence = models.ForeignKey(
        'self', blank=True, null=True, editable=False, related_name='associated'
    )
    # Use this for symmetric relationship.
    #occurrence = models.ManyToManyField(
        #'self', blank=True, null=True, editable=False,
    #)
    number = models.PositiveIntegerField(
        _(u'Number'), serialize=True, default=0,
        auto_created=True, editable=False,
        unique_for_year='start_ts')
    start_ts = models.DateTimeField(
        _(u'Time'), auto_now_add=True, editable=False)
    end_ts = models.DateTimeField(
        _(u'Time Ended'), editable=False, null=True)
    importance = models.ForeignKey(Importance, verbose_name=_(u'Importance'), default=1)
    status = models.ForeignKey(Status, verbose_name=_(u'Status'), default=1)
    nature = models.ForeignKey(Nature, default=1)
    description = models.TextField(_(u'Description'), blank=True)
    entity = models.ForeignKey(Entity, verbose_name=_(u'Unit'), blank=True, null=True)
    # Location Fields
    district = models.ForeignKey(District, verbose_name=_(u'District'), blank=True, null=True)
    county = models.ForeignKey(County, verbose_name=_(u'Subdistrict'), blank=True, null=True)
    locality = models.ForeignKey(Locality, verbose_name=_(u'Suco'), blank=True, null=True)
    local = models.CharField(_(u'Aldea'), max_length=256, blank=True)
    point_of_reference = models.TextField(_(u'Point of Reference'), blank=True)
    # Geolocation Fields
    latitude = models.FloatField(_(u'Latitude'), blank=True, null=True)
    longitude = models.FloatField(_(u'Longitude'), blank=True, null=True)

    @models.permalink
    def get_absolute_url(self):
        return ('occurrence_edit', [self.pk, ])

    def save(self, *args, **kwargs):
        from datetime import datetime
        if self.status.pk in (5, 7):
            self.end_ts = datetime.now()
        return super(Occurrence, self).save(*args, **kwargs)


class ResourceType(models.Model):
    name = models.CharField(_(u'Name'), max_length=256)

    def __unicode__(self):
        return self.name


class Resource(models.Model):
    name = models.CharField(_(u'Name'), max_length=256)
    resource_type = models.ForeignKey(
        ResourceType, verbose_name=_(u'Type'), editable=True)

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('resource_edit', [self.pk, ])


class DispatchStatus(models.NamedModel):
    name = models.CharField(_(u'Name'), max_length=256)

    class Meta:
        verbose_name = _(u'Dispatch Status')
        verbose_name_plural = _(u'Dispatch Statuses')
        verbose_name = _lazy(u'Dispatch Status')
        verbose_name_plural = _lazy(u'Dispatch Statuses')


class Dispatch(models.Model):
    user = models.ForeignKey(User, editable=False)
    occurrence = models.ForeignKey(
        Occurrence, verbose_name=_(u'Occurrence'), editable=False)
    entity = models.ForeignKey(

incident/forms.py
__LICENSE__ = '''Copyright (C) 2012 "Emanuel Calso" <eman@bloodpet.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see
http://www.gnu.org/licenses/agpl-3.0.html.
'''


from django import forms


# vim: set expandtab ts=4 filetype=python fileencoding=utf-8 ai

templates/incident/alert_detail.html
{% extends "base.html" %}
{% load i18n %}

{% comment %}
Copyright (C) 2012 "Emanuel Calso" <eman@xaasy.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see
http://www.gnu.org/licenses/agpl-3.0.html.
{% endcomment %}

{% block title %}{% trans 'Alert Details' %}{% endblock %}
{% block page_title %}{{ alert.title }} {% trans 'Alert Details' %}{% endblock %}

{% block content %}
<div class="stackContent">
	<dl>
		<dt>{% trans 'Number' %}</dt>
		<dd>{{ alert.number }}</dd>
	</dl>
	<span>
		<a href="{% url alert_list %}" role="button"
			title="{% trans 'Back to List' %}">
			<span class="ui-icon ui-icon-document icon-right"></span>
			{% trans 'Back to List' %}</a>
		<a href="{% url alert_edit alert.pk %}" role="button"
			title="{% trans 'Edit' %}">
			<span class="ui-icon ui-icon-pencil icon-right"></span>
			{% trans 'Edit' %}</a>
		<a href="{% url alert_edit alert.pk %}" role="button"
			title="{% trans 'Associate Alert to an Occurrence' %}">
			<span class="ui-icon ui-icon-extlink icon-right"></span>
			{% trans 'Associate Alert to an Occurrence' %}</a>
	</span>
</div><!-- .stackContent -->
{% endblock content %}

templates/incident/occurrence_detail.html
{% extends "base.html" %}
{% load i18n %}

{% comment %}
Copyright (C) 2012 "Emanuel Calso" <eman@xaasy.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see
http://www.gnu.org/licenses/agpl-3.0.html.
{% endcomment %}

{% block title %}{% trans 'Occurrence Details' %}{% endblock %}
{% block page_title %}{{ occurrence.title }} {% trans 'Occurrence Details' %}{% endblock %}

{% block content %}
<div class="stackContent">
	<dl>
		<dt>{% trans 'Number' %}</dt>
		<dd>{{ occurrence.number }}</dd>
	</dl>
	<span>
		<a href="{% url occurrence_list %}" role="button"
			title="{% trans 'Back to List' %}">
			<span class="ui-icon ui-icon-document icon-right"></span>
			{% trans 'Back to List' %}</a>
		<a href="{% url occurrence_edit occurrence.pk %}" role="button"
			title="{% trans 'Edit' %}">
			<span class="ui-icon ui-icon-pencil icon-right"></span>
			{% trans 'Edit' %}</a>
	</span>
</div><!-- .stackContent -->
{% endblock content %}

templates/incident/occurrence_form.html
{% extends "base_occurrence.html" %}
{% load i18n %}

{% comment %}
Copyright (C) 2012 "Emanuel Calso" <eman@xaasy.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see
http://www.gnu.org/licenses/agpl-3.0.html.
{% endcomment %}

{% block title %}{{ page_title }}{% endblock %}
{% block page_title %}{{ page_title }}{% endblock %}

{% block toolbar %}
{% if not is_new %}
	<div class="stack1of3"><a class="stackContent remove-entry" href="#">{% trans "Remove" %}</a></div>
	<div class="stack1of3"><a class="stackContent" href="{% url occurrence_associate object.pk %}">{% trans "Associate Related Occurrence" %}</a></div>
	<div class="stack1of3"><a class="stackContent close" href="#">{% trans "Close" %}</a></div>
	<form class="hidden" id="table-form" method="post" action="{% url occurrence_list %}">{% csrf_token %}
		<input type="hidden" name="action" id="action-input" />
		<input type="hidden" name="select" value="{{ object.pk }}" />
	</form>
{% endif %}
{% endblock %}

{% block content %}
<div class="stackContent">
	<h2>{{ page_title }}</h2>
	<form method="post" id="occurrence-form" class="autosave">{% csrf_token %}
		<div class="stack left">
			<div class="stack1of5"><div class="stackContent right">
				<label for="id_date">{% trans "Date" %}</label>
			</div></div>
			<div class="stack1of5"><div class="stackContent">
				<input type="date" id="id_date" name="date" value="{{ object.start_ts|date:"Y-m-d" }}" />
			</div></div>
			<div class="stack1of5"><div class="stackContent right">
				<label for="id_time">{% trans "Time" %}</label>
			</div></div>
			<div class="stack1of5"><div class="stackContent">
				<input type="time" id="id_time" name="time" value="{{ object.start_ts|date:"H:i:s" }}" />
			</div></div>
			<div class="clear"></div>

			<div class="stack1of5"><div class="stackContent right">
				<label for="id_nature">{% trans "Nature" %}</label>
			</div></div>
			<div class="stack4of5"><div class="stackContent">
				{{ form.nature }}
			</div></div>

			<div class="stack1of5"><div class="stackContent right">
				<label for="id_status">{% trans "Status" %}</label>
			</div></div>
			<div class="stack4of5"><div class="stackContent">
				{{ form.status }}
			</div></div>

			<div class="stack1of5"><div class="stackContent right">
				<label for="id_importance">{% trans "Importance" %}</label>
			</div></div>
			<div class="stack4of5"><div class="stackContent">
				{{ form.importance }}
			</div></div>

			<div class="stack1of5"><div class="stackContent right">
				<label for="id_description">{% trans "Description" %}</label>
			</div></div>
			<div class="stack4of5"><div class="stackContent">
				{{ form.description }}
			</div></div>

			<fieldset>
				<legend class="stackContent">{% trans "Unit Responsible" %}</legend>
				<div class="stack1of5"><div class="stackContent right">
					<label for="id_entity">{% trans "Unit" %}</label>
				</div></div>
				<div class="stack4of5"><div class="stackContent">
					{{ form.entity }}
				</div></div>
			</fieldset>

			<fieldset>

				<legend class="stackContent">{% trans "Location" %}</legend>

				<div class="stack1of5"><div class="stackContent right">
					<label for="id_district">{% trans "District" %}</label>
				</div></div>
				<div class="stack4of5"><div class="stackContent">
					{{ form.district }}
				</div></div>

				<div class="stack1of5"><div class="stackContent right">
					<label for="id_county">{% trans "Subdistrict" %}</label>
				</div></div>
				<div class="stack4of5"><div class="stackContent">
					{{ form.county }}
				</div></div>

				<div class="stack1of5"><div class="stackContent right">
					<label for="id_locality">{% trans "Suco" %}</label>
				</div></div>
				<div class="stack4of5"><div class="stackContent">
					{{ form.locality }}
				</div></div>

				<div class="stack1of5"><div class="stackContent right">
					<label for="id_local">{% trans "Aldea" %}</label>
				</div></div>
				<div class="stack4of5"><div class="stackContent">
					{{ form.local }}
				</div></div>

				<div class="stack1of5"><div class="stackContent right">
					<label for="id_point_of_reference">{% trans "Point of Reference" %}</label>
				</div></div>
				<div class="stack4of5"><div class="stackContent">
					{{ form.point_of_reference }}
				</div></div>

			</fieldset>

		</div>
	</form>
</div><!-- .stackContent -->
{% endblock content %}

{% block extra_script %}
{% if not is_new %}
<script type="text/javascript">
	$(function(){
		function check_required() {
			if ($('#id_entity').val()) {
				return true;
			} else {
			alert('{% trans "Please choose an entity" %}');
				return false;
			}
		}
		//$('.shortcut a').click(check_required);
		//$('.main-menu a[href="{% url dispatches object.pk %}"]').click(check_required);
		$('.close').click(function() {
			$('#occurrence-form').submit()
		});
		$('.close').click(function() {
			$('#occurrence-form').submit()
		});
		$('#occurrence-form').validate({
			rules: {
				nature: 'required',
				entity: 'required',
				//source_type: 'required',
				date: 'required',
				time: 'required'
			}
		});
	});
</script>
{% endif %}
{% endblock %}

templates/incident/resource_detail.html
{% extends "base.html" %}
{% load i18n %}

{% comment %}
Copyright (C) 2012 "Emanuel Calso" <eman@xaasy.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see
http://www.gnu.org/licenses/agpl-3.0.html.
{% endcomment %}

{% block title %}{% trans 'Resource Details' %}{% endblock %}
{% block page_title %}{{ resource.title }} {% trans 'Resource Details' %}{% endblock %}

{% block content %}
<div class="stackContent">
	<dl>
		<dt>{% trans 'Name' %}</dt>
		<dd>{{ resource.name }}</dd>
		<dt>{% trans 'Type' %}</dt>
		<dd>{{ resource.resource_type.name }}</dd>
	</dl>
	<span>
		<a href="{% url resource_list %}" role="button"
			title="{% trans 'List' %}">
			<span class="ui-icon ui-icon-document icon-right"></span>
			{% trans 'List' %}</a>
		<a href="{% url resource_edit resource.pk %}" role="button"
			title="{% trans 'Edit' %}">
			<span class="ui-icon ui-icon-pencil icon-right"></span>
			{% trans 'Edit' %}</a>
	</span>
</div><!-- .stackContent -->
{% endblock content %}